version: "3.6"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw12#
    volumes:
      - mssql:/var/opt/mssql
volumes:
  mssql:

